import asyncio
from types import SimpleNamespace

from gregg_limper.formatter import format_message, classify
from gregg_limper.formatter.model import TextFragment, LinkFragment


class DummyMessage(SimpleNamespace):
    pass


async def run(coro):
    return await coro


def make_message(content="", attachments=None):
    attachments = attachments or []
    return DummyMessage(
        content=content,
        attachments=attachments,
        id=42,
        author=SimpleNamespace(display_name="Tester"),
        channel=SimpleNamespace(id=7),
        guild=SimpleNamespace(id=3),
    )


def test_classify_splits_text_and_links():
    msg = make_message("Check this https://example.com")
    result = classify(msg)
    assert "text" in result and result["text"] == "Check this"
    assert result["link"] == ["https://example.com"]


async def _fake_summarize_url(url, enable_citations=True):
    return f"summary of {url}"


def test_format_message_end_to_end(monkeypatch):
    # Patch network-heavy summarization
    monkeypatch.setattr(
        "gregg_limper.formatter.handlers.link.summarize_url", _fake_summarize_url
    )
    msg = make_message("Look https://example.com")
    result = asyncio.run(format_message(msg))
    assert result["author"] == "Tester"
    frags = result["fragments"]
    assert len(frags) == 2
    assert isinstance(frags[0], TextFragment)
    assert frags[0].description == "Look"
    assert isinstance(frags[1], LinkFragment)
    assert frags[1].description == "summary of https://example.com"
    # ids generated by stable_media_id should not be empty
    assert frags[0].id and frags[1].id
